name: bemol_test
description: Flutter tech challenge for BEMOL DIGITAL
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
